### ISSUE TITLE
Exiting 1st-person camera sets camera to wrong position (where it left beforehand)

### ISSUE THREAD

**Issue by Vectorial1024** [Asu4ni/CitiesSkylines-FPSCamera#10]
When I press esc to exit 1st person camera, the camera is placed at the position where I originally entered the 1st-person camera mode.

**Comment by Asu4ni** [comment]
That is the intended behavior, which is the same as what the original mod does. It is possible to add an extra option to let user choose whether to stay at the same position or to return to where it left. What do you think?

**Comment by Vectorial1024** [comment]
It is a bit confusing, but the "original mod" is this right? https://steamcommunity.com/sharedfiles/filedetails/?id=650805785

For me, sometimes I get bored and just select a public transport vehicle and go into first-person mode. This way I can just chill and look at my city from another angle, makes me feel like I am living inside it. So I agree there should be an option to let users select whether to return to the original position or just set the camera to where it currently is at.

**Comment by Asu4ni** [comment]
The option is added by 950cc3324f188a43966704be48c8a39153725f69

**Comment by Asu4ni** [comment]
There's a fix from a3c2a2390a39771bce32d9288947a7092b4ace07
