### ISSUE TITLE
Pressing esc sometimes pauses the game

### ISSUE THREAD

**Issue by Vectorial1024** [Asu4ni/CitiesSkylines-FPSCamera#11]
When pressing esc in 1st-person camera mode to exit the mode, the mode is exited, but sometimes the game also pauses and enters the pause menu.

**Comment by Asu4ni** [comment]
The game pauses and shows the menu when pressing Esc is what the game originally behaves. The mod only sees that Esc is pressed and exits the mode. I guess that if we'd like to prevent this from happening, we have to eat the input so that the game do not get the trigger. It'll take some time for me to figure out how this could be done. Maybe anyone here familiar with the input handling can contribute as well.

**Comment by Asu4ni** [comment]
From my initial lookup,  `eventKeyDown` should probably be used instead of `Input.GetKeyDown`. `UIKeyEventParameter.Use()` should consume the input in this case. I'll try to incorporate them soon

**Comment by Asu4ni** [comment]
It should be solved by 5d81c30fadef47ce6f2c1895e91f50f6fdb43aaa.

@Vectorial1024 You could check whether it works now if you'd willing to compile it yourself. Otherwise, please report back here if there are still problems in the next release.

**Comment by Vectorial1024** [comment]
Thanks for the help! I'd be waiting for the next release to come out and report back. I actually found a few other issues (this is beta after all) so perhaps it is better to group things a bit.

**Comment by Vectorial1024** [comment]
I noticed that the update was posted.

Just want to point out an edge case for others to see: after the udpate, sometimes I cannot exit the 1st person mode using ESC (it always pauses the game instead). After some more testing, I reset the mod settings and reassigned the "exit 1st person mode" key to DEL, and now ESC works again to exit 1st person mode.

-----

Besides that, this is working well!

**Comment by Asu4ni** [comment]
A problem is still present: 

Sometimes, pressing `Esc` has no impact on the mod. It should result from the focus shifted away so that the `KeyDownEvent` is not received by the mod.

**Comment by Asu4ni** [comment]
solved by 1bdabc73820c474eb1fddabe29564dc328d96f24
which uses patching by Harmony
