### ISSUE TITLE
Entering 1st person mode retains UI info panel

### ISSUE THREAD

**Issue by Vectorial1024** [Asu4ni/CitiesSkylines-FPSCamera#13]
For example:

![Screenshot](https://user-images.githubusercontent.com/17726797/158047433-5f32e4f2-a25d-45e3-a1f2-627cc1e05111.png)

After I enter 1st-person mode of this vehicle, the UI becomes this:

![Screenshot](https://user-images.githubusercontent.com/17726797/158047435-770e5858-d08a-49ea-a884-cbcb69d08707.png)

Having the UI info panel still appearing, this is kind of ruining the 1st-person camera vision... This is especially true after I unpause it, in which the info panel will start "glitching" and jump up and down at the left side of the screen. I understand this "glitching" behavior can be due to camera rending math not being accurate, but I will have to pause the game to freeze the camera, so that the info panel stops jumping and I can click on the X to close it.

**Comment by Asu4ni** [comment]
Great idea! This should be possible.

**Comment by Asu4ni** [comment]
Added in d5ad727ffef1673b0b47866199d8a094cea41a8e
