### ISSUE TITLE
Improve camera positioning for following vehicles

### ISSUE THREAD

**Issue by Vectorial1024** [Asu4ni/CitiesSkylines-FPSCamera#18]
I am using the Steam version on 14 Mar. (or 13 Mar depending on the timezone, you get it)

For example:

![Screenshot](https://user-images.githubusercontent.com/17726797/158096350-fa1dde31-3f6f-4c07-962d-89f17d041181.png)

From the blue highlights of the parked car on the left, we could see that the 1st-person camera is placed inside the vehicle model. This means I can no longer select anything outside the vehicle, because the raytracing means that it will always hit the vehicle that I am already inside of.

**Comment by Asu4ni** [comment]
This is really a pain to solve I guess. For now, you could use _Vehicle cam offset_ in the option menu or simply move the camera forward each time to get outside the car. In the future, we might support setting the correct camera position offset for each type of vehicles somehow.

**Comment by Vectorial1024** [comment]
It was a while before I discovered that I could move the camera forward, so I guess it is OK for now.

**Comment by Asu4ni** [comment]
Added by 9e603a681b49602cb756f96384867b9bd30edd21
