### ISSUE TITLE
Unknown mod options section

### ISSUE THREAD

**Issue by Vectorial1024** [Asu4ni/CitiesSkylines-FPSCamera#19]
For example, looking at the bottom of the mod options panel:

![Screenshot](https://user-images.githubusercontent.com/17726797/158096899-409a24a9-9274-4b11-9c7b-cd8c2805b025.png)

Could this be related to the new option #10 ?

**Comment by Asu4ni** [comment]
removed in 86881a0764b7055a4348d1c4b8d6b04296446be8
