### ISSUE TITLE
Mod Options is slightly blue

### ISSUE THREAD

**Issue by Vectorial1024** [Asu4ni/CitiesSkylines-FPSCamera#39]
It has been a while. When I revisited the game + the mod options recently, I noticed that the mod options of this mod is slightly blue. EG, usually the mod options UI text is white, but the options UI text of this mod has the blue color.

![Screenshot](https://user-images.githubusercontent.com/17726797/165345300-d3925c5a-470f-4c96-925c-a180ef2c5d21.png)

**Comment by Asu4ni** [comment]
This is intentional. Most of the UI elements of the mod use the same color palette.
