### ISSUE TITLE
mouse-move camera rotate around object with an radius

### ISSUE THREAD

**Issue by lokpro** [Asu4ni/CitiesSkylines-FPSCamera#52]
Hi,
I hope this mod have [this](https://www.researchgate.net/profile/Yang-Xiao-90/publication/329899720/figure/fig2/AS:708273472798720@1545876963302/Rotation-of-the-virtual-camera-within-3D-space-to-mimic-different-imaging-viewpoints-in.jpg) type of camera rotation like GTA game, which I move the camera around the object instead of the real first-person view.

I suggest maybe implement a camera distance from to the object. Setting it greater than zero to achieve this effect.

Thanks.

**Comment by Asu4ni** [comment]
Hey @lokpro, appreciate your time for giving suggestions. I'd like to understand your idea first though.

By simply reading your description, it seems that what you want is a third-person camera, which also functions mostly the same as the built-in following/tracking option:
![image](https://user-images.githubusercontent.com/14138331/186161935-400f0b37-4f6c-4762-8377-394226948b96.png).

If I did misunderstand your idea, please elaborate a bit further.

**Comment by lokpro** [comment]
Yes, I have figured out it is called Third-person View, vs FPV.

I used to use this [City drive](https://steamcommunity.com/sharedfiles/filedetails/?id=844180955) mod, not now because it is incompatible with TM:PE. [Video at 1:39](https://youtu.be/0u10zwq-0Vs?t=99) shows its FPV. It rotates the camera with mouse in [this way](https://www.researchgate.net/profile/Yang-Xiao-90/publication/329899720/figure/fig2/AS:708273472798720@1545876963302/Rotation-of-the-virtual-camera-within-3D-space-to-mimic-different-imaging-viewpoints-in.jpg) instead of turning the (tiny) head in first person view.

And yes, it is the same feeling as the game's built-in following feature. I have just tried it. However, the things are:
1. rotate camera with mouse-mid-button holding - it's OK.
2. can't go under flyovers and inside tunnels.
3. (CMIIW) I can zoom in close to the vehicle/cim just because I have [ACME](https://steamcommunity.com/sharedfiles/filedetails/?id=2778750497) , else I can't zoom close to it.

So far it's OK for me to enjoy watching the driving with FPSCamera2.
But if implementing this function is as simply as just adding a _Radius_ field, and offsetting the camera backwards by _Radius_, then I Suggest doing this to add value to the current mod.

Thank you for your reply and your team's effort.

**Comment by Asu4ni** [comment]
I got it. I guess it is already partly implemented in the mod, and maybe you missed it. You could offset the camera in follow mode as described [here](https://github.com/Asu4ni/CitiesSkylines-FPSCamera/wiki/Camera-Mode#Follow-Mode). But the current way of control is not the same as what you described.
For now, you could offset the camera position and adjust the angle so that it looks like watching the following target by the side / behind.

**Comment by lokpro** [comment]
Hi，我研究了一陣子，看來只要改一下下就差不多是 TPV 了，就取代這段，還差把車子放在screen正中間。

(3D 或 C:S mod 我都是第一次碰)
(發現了你是台灣人，寫中文好了)

```c#
            var RADIUS = -30f;
            var position = TargetPositioning.position.Move(
            new LocalMovement { forward = RADIUS }
                    .AsDisplacementAt( _targetSetting.positioning.angle )
            );

            base.Positioning = new Positioning(
                smoothMove ? current.positioning.position.AdvanceToTarget(
                                 position, advanceRatio,
                                 new Range(Config.G.MinTransMove, Config.G.MaxTransMove)) :
                             position,
                smoothAngle ? current.positioning.angle.AdvanceToTarget(
                                  _targetSetting.positioning.angle, advanceRatio,
                                  new Range(Config.G.MinTransRotate, Config.G.MaxTransRotate)) :
                              _targetSetting.positioning.angle
            );
```

https://github.com/Asu4ni/CitiesSkylines-FPSCamera/blob/d1fc0d97508f5fd4479b46578c2f41471e4c71bd/FPSCamera/GameCam.cs#L43-L52


---

Btw, 我用起來覺得動得太慢，我自己改成 0.5f 
https://github.com/Asu4ni/CitiesSkylines-FPSCamera/blob/d1fc0d97508f5fd4479b46578c2f41471e4c71bd/FPSCamera/Controller.cs#L154-L155

**Comment by Asu4ni** [comment]
Hey, I'd suggest that we keep any discussion here in English for everyone to be able to participate.

btw, mouse rotation sensitivity can be adjusted in settings.
